spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
server:
  port: 8001
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8002/eureka/
    fetch-registry: true
    register-with-eureka: true
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 8001
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/
    fetch-registry: true
    register-with-eureka: true